site_name: SideChef

repo_name: fga-eps-mds/2025.1-AppReceitas-Docs
repo_url: https://github.com/fga-eps-mds/2025.1-AppReceitas-Docs

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
  
nav: 
  - Início: index.md
  - Artefatos:
    - Documentação da Arquitetura: artefatos/arquitetura.md
    - Lean Inception: artefatos/leaninception.md
  - Planejamento: 
    - Comunicação: planejamento/comunicacao.md
    - Conhecimento: planejamento/conhecimento.md
    - Custos: planejamento/custos.md
    - Riscos: planejamento/riscos.md
    - Tempo: planejamento/tempo.md
  - Sprints:
    - Atas Reuniões: 
      - Reunião 1 (Lean Inception): sprints/atas_reunioes/ata1.md
      - Reunião 2 (Lean Inception): sprints/atas_reunioes/ata2.md
      - Reunião 3 (Lean Inception): sprints/atas_reunioes/ata3.md
    - Sprint 1: 
      - Planning 1: sprints/Sprint_1/planning.md
  - Políticas: 
    - Politica de commmits: politicas/politica_commits.md
